# Generated by Django 5.1.3 on 2024-11-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('year_levels', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=255)),
                ('vimeo_id', models.CharField(max_length=30)),
                ('image_link', models.URLField(default='')),
                ('type', models.CharField(default='Noval', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=6)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(default='1', max_length=10)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='1', max_length=255)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='engine.film')),
            ],
        ),
    ]
